# General Jekyll Config
pygments: true
url: http://dmd1070.github.io/
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#4EA3D0'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: DMD1070
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: adamdscott
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: DMD1070
  email: test@example.com
  tagline: Fundamentals of Web Design

  excerpt_separator: <!--more-->

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
